/* Formatted on 04/05/2024 13:57:20 (QP5 v5.215.12089.38647) */
/***/

/* ANONYMOUS BLOCK UNTUK MENCARI NAMA, ALAMAT, NILAI_PENGAJUAN BERDASARKAN NIK TERTENTU */

DECLARE
    V_NAMA_DEBITUR      KUR_T_DEBITUR.NAMA%TYPE;
    V_ALAMAT            KUR_T_DEBITUR.ALAMAT%TYPE;
    V_NILAI_PENGAJUAN   NUMBER;
BEGIN
    SELECT NAMA, ALAMAT, JML_KREDIT
      INTO V_NAMA_DEBITUR, V_ALAMAT, V_NILAI_PENGAJUAN
      FROM KUR_T_DEBITUR
     WHERE NIK = '7402101001840006';

    DBMS_OUTPUT.PUT_LINE ('Debitur dengan nama ' || V_NAMA_DEBITUR || ' yang beralamat di ' || V_ALAMAT || ' mengajukan KUR senilai ' || V_NILAI_PENGAJUAN);
END;

/***/
/* ANONYMOUS BLOCK UNTUK MENGAMBIL SEMUA ROW DARI TABEL KUR_T_DEBITUR BERDASARKAN NIK TERTENTU DENGAN TYPE DATA KOLOM MENGIKUTI KOLOM PADA TABEL REFERENSINYA */

DECLARE
    L_DEBITUR   KUR_T_DEBITUR%ROWTYPE;
BEGIN
    SELECT *
      INTO L_DEBITUR
      FROM KUR_T_DEBITUR
     WHERE NIK = '7402101001840006';

    DBMS_OUTPUT.PUT_LINE ('NAMA: ' || L_DEBITUR.NAMA || ', NIK: ' || L_DEBITUR.NIK || ', ALAMAT: ' || L_DEBITUR.ALAMAT);
END;

/***/
/* ANONYMOUS BLOCK UNTUK MENGAMBIL KOLOM DARI BEBERAPA TABEL BERDASARKAN NIK TERTENTU DENGAN TYPE DATA KOLOM MENGIKUTI KOLOM PADA TABEL REFERENSINYA */

DECLARE
    V_DEBITUR   KUR_T_DEBITUR.NAMA%TYPE;
    V_BANK      KUR_R_BANK.NAMA_BANK%TYPE;
    V_KOTA      KUR_R_WILAYAH.NAMA_WILAYAH%TYPE;
BEGIN
    SELECT A.NAMA, UPPER (B.NAMA_WILAYAH), UPPER (C.NAMA_BANK)
      INTO V_DEBITUR, V_KOTA, V_BANK
      FROM KUR_T_DEBITUR A, KUR_R_WILAYAH B, KUR_R_BANK C
     WHERE A.KODE_KABKOTA = B.KODE_WILAYAH AND A.KODE_BANK = C.KODE_BANK AND A.NIK = '7402101001840006';

    DBMS_OUTPUT.PUT_LINE (V_DEBITUR || ' dari ' || V_KOTA || ' yang diupload oleh ' || V_BANK);
END;