/* Formatted on 12/01/2026 6:08:22 (QP5 v5.215.12089.38647) */
  SELECT TO_CHAR (LOG_DATE, 'YYYY-MM-DD HH24:MI:SS') LOG_DATE,
         OWNER,
         JOB_NAME,
         STATUS,
         TO_CHAR (REQ_START_DATE, 'YYYY-MM-DD HH24:MI:SS') REQ_START_DATE,
         TO_CHAR (ACTUAL_START_DATE, 'YYYY-MM-DD HH24:MI:SS') ACTUAL_START_DATE,
         RUN_DURATION,
         ADDITIONAL_INFO
    FROM USER_SCHEDULER_JOB_RUN_DETAILS
ORDER BY LOG_DATE DESC;

SELECT *
  FROM ALL_OBJECTS
 WHERE OBJECT_NAME LIKE '%USER_SCHEDULER_JOB_RUN_DETAILS%';


/* LAKUKAN HAL-HAL INI SEBELUM DROP TABLE */

/* 
1. MENGECEK INDEX SEBELUM DROP TABLE 
*/

SELECT INDEX_NAME, UNIQUENESS
  FROM USER_INDEXES
 WHERE TABLE_NAME = 'T_PENYEBAB_RISIKO';

SELECT UC.CONSTRAINT_NAME, UI.INDEX_NAME
  FROM USER_CONSTRAINTS UC JOIN USER_INDEXES UI ON UC.INDEX_NAME = UI.INDEX_NAME
 WHERE UC.TABLE_NAME = 'T_PENYEBAB_RISIKO';

/* 
2. MENGECEK CONSTRAINT SEBELUM DROP TABLE 
P - Primary Key
R - Foreign Key/ References
U - Unique
C - Check
*/

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'T_PENYEBAB_RISIKO';

/* 
3. CEK FOREIGN KEY DARI TABEL LAIN YANG MEREFERENSIKAN TABEL INI 
*/

SELECT A.CONSTRAINT_NAME, A.TABLE_NAME
  FROM USER_CONSTRAINTS A
 WHERE     A.CONSTRAINT_TYPE = 'R'
       AND A.R_CONSTRAINT_NAME IN (SELECT CONSTRAINT_NAME
                                     FROM USER_CONSTRAINTS
                                    WHERE TABLE_NAME = 'T_PENYEBAB_RISIKO');

/* 
4. LAKUKAN BACKUP DDL CONSTRAINT DAN INDEX 
*/

SELECT DBMS_LOB.SUBSTR (DDL_SCRIPT, 4000) AS DDL_SCRIPT
  FROM (SELECT DBMS_METADATA.GET_DDL ('TABLE', 'T_PENYEBAB_RISIKO') AS DDL_SCRIPT FROM DUAL);

/*
5. LAKUKAN DROP TABLE DENGAN HATI-HATI (Gunakan CASCADE CONSTRAINTS hanya jika yakin)
*/