/* Formatted on 27/04/2024 05:41:57 (QP5 v5.391) */
  SELECT TO_CHAR (LOG_DATE, 'YYYY-MM-DD HH24:MI:SS') LOG_DATE,
         OWNER,
         JOB_NAME,
         STATUS,
         TO_CHAR (REQ_START_DATE, 'YYYY-MM-DD HH24:MI:SS') REQ_START_DATE,
         TO_CHAR (ACTUAL_START_DATE, 'YYYY-MM-DD HH24:MI:SS') ACTUAL_START_DATE,
         RUN_DURATION,
         ADDITIONAL_INFO
    FROM USER_SCHEDULER_JOB_RUN_DETAILS
ORDER BY LOG_DATE DESC;

SELECT * FROM ALL_OBJECTS WHERE OBJECT_NAME LIKE '%USER_SCHEDULER_JOB_RUN_DETAILS%'