/* Formatted on 29/02/2024 15:23:30 (QP5 v5.215.12089.38647) */
SELECT A.KDSATKER,
       A.THANG,
       --NULL AS NOURUT,
       CASE WHEN A.PAGU <> D.PAGU THEN NVL (D.NOURUT, 0) + 1 ELSE D.NOURUT END AS NOURUT,
       A.PAGU AS BATASALOKASI,
       0 AS SISA_TAYL,
       0 AS GUNA_TAYL,
       A.PAGU AS NILAIALOKASI,
       0 AS NILAIALOKASI_SBLM,
       A.PAGU AS NILAIALOKASI_SD,
       7 AS STATUS,
       SYSDATE AS CREATED_AT,
       SYSDATE AS UPDATED_AT,
       100 AS REKOMENDASI,
       A.PAGU AS NILAIALOKASI_FINAL,
       100 AS PERSEN_FINAL,
       CASE WHEN A.PAGU <> D.PAGU THEN NVL (D.NOURUT, 0) + 1 ELSE D.NOURUT END AS NO_KANWIL,
       --NULL AS NO_KANWIL,
       CASE WHEN A.PAGU <> D.PAGU THEN SYSDATE ELSE NVL (D.TGL_KANWIL, SYSDATE) END AS TGL_KANWIL
  --NULL AS TGL_KANWIL
  FROM MP_D_PAGU A
       JOIN MP_R_SATKER_MPP B
          ON (A.KDSATKER || A.THANG = B.KDSATKER || B.THANG)
       JOIN (  SELECT KDSATKER, THANG, MAX (REALISASI) AS REALISASIMAX
                 FROM MPT_D_ALOKASI
                WHERE THANG = '2022'
             GROUP BY KDSATKER, THANG) C
          ON (A.KDSATKER || A.THANG = C.KDSATKER || C.THANG)
       JOIN MPT_D_ALOKASI D
          ON (C.KDSATKER || C.THANG = D.KDSATKER || D.THANG AND C.REALISASIMAX = D.REALISASI);


SELECT *
  FROM MP_D_PAGU
 WHERE THANG = '2022' AND KDSATKER = '686129';

SELECT *
  FROM MP_R_SATKER_MPP
 WHERE THANG = '2022' AND KDSATKER = '686129';

SELECT *
  FROM MPT_D_ALOKASI
 WHERE     THANG = '2022'
       AND REALISASI IN (  SELECT KDSATKER, THANG, MAX (REALISASI) AS REALISASIMAX
                             FROM MPT_D_ALOKASI
                            WHERE THANG = '2022'
                         GROUP BY KDSATKER, THANG);