/* Formatted on 26/09/2025 18:01:20 (QP5 v5.215.12089.38647) */
  SELECT kode_wilayah,
         kode_bank,
         skema,
         sektor,
         SUM (CASE WHEN bulan = '01' THEN jml_debitur ELSE 0 END) AS jd01,
         SUM (CASE WHEN bulan = '02' THEN jml_debitur ELSE 0 END) AS jd02,
         SUM (CASE WHEN bulan = '03' THEN jml_debitur ELSE 0 END) AS jd03,
         SUM (CASE WHEN bulan = '04' THEN jml_debitur ELSE 0 END) AS jd04,
         SUM (CASE WHEN bulan = '05' THEN jml_debitur ELSE 0 END) AS jd05,
         SUM (CASE WHEN bulan = '06' THEN jml_debitur ELSE 0 END) AS jd06,
         SUM (CASE WHEN bulan = '07' THEN jml_debitur ELSE 0 END) AS jd07,
         SUM (CASE WHEN bulan = '08' THEN jml_debitur ELSE 0 END) AS jd08,
         SUM (CASE WHEN bulan = '09' THEN jml_debitur ELSE 0 END) AS jd09,
         SUM (CASE WHEN bulan = '10' THEN jml_debitur ELSE 0 END) AS jd10,
         SUM (CASE WHEN bulan = '11' THEN jml_debitur ELSE 0 END) AS jd11,
         SUM (CASE WHEN bulan = '12' THEN jml_debitur ELSE 0 END) AS jd12,
         SUM (CASE WHEN bulan IN ('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12') THEN jml_debitur ELSE 0 END) AS jdtotal,
         SUM (CASE WHEN bulan = '01' THEN jml_penyaluran ELSE 0 END) AS jp01,
         SUM (CASE WHEN bulan = '02' THEN jml_penyaluran ELSE 0 END) AS jp02,
         SUM (CASE WHEN bulan = '03' THEN jml_penyaluran ELSE 0 END) AS jp03,
         SUM (CASE WHEN bulan = '04' THEN jml_penyaluran ELSE 0 END) AS jp04,
         SUM (CASE WHEN bulan = '05' THEN jml_penyaluran ELSE 0 END) AS jp05,
         SUM (CASE WHEN bulan = '06' THEN jml_penyaluran ELSE 0 END) AS jp06,
         SUM (CASE WHEN bulan = '07' THEN jml_penyaluran ELSE 0 END) AS jp07,
         SUM (CASE WHEN bulan = '08' THEN jml_penyaluran ELSE 0 END) AS jp08,
         SUM (CASE WHEN bulan = '09' THEN jml_penyaluran ELSE 0 END) AS jp09,
         SUM (CASE WHEN bulan = '10' THEN jml_penyaluran ELSE 0 END) AS jp10,
         SUM (CASE WHEN bulan = '11' THEN jml_penyaluran ELSE 0 END) AS jp11,
         SUM (CASE WHEN bulan = '12' THEN jml_penyaluran ELSE 0 END) AS jp12,
         SUM (CASE WHEN bulan IN ('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12') THEN jml_penyaluran ELSE 0 END) AS jptotal
    FROM (SELECT *
            FROM kur_a_custom_report
           WHERE tahun = :ptahun AND SUBSTR (kode_wilayah, 1, 2) = :pkabkota AND kode_bank = :pbank)
GROUP BY kode_wilayah,
         kode_bank,
         skema,
         sektor
ORDER BY 1,
         2,
         3,
         4;

  SELECT kode_bank,
         skema,
         sektor,
         kode_wilayah,
         SUM (CASE WHEN bulan = '01' THEN jml_debitur ELSE 0 END) AS jd01,
         SUM (CASE WHEN bulan = '02' THEN jml_debitur ELSE 0 END) AS jd02,
         SUM (CASE WHEN bulan = '03' THEN jml_debitur ELSE 0 END) AS jd03,
         SUM (CASE WHEN bulan = '04' THEN jml_debitur ELSE 0 END) AS jd04,
         SUM (CASE WHEN bulan = '05' THEN jml_debitur ELSE 0 END) AS jd05,
         SUM (CASE WHEN bulan = '06' THEN jml_debitur ELSE 0 END) AS jd06,
         SUM (CASE WHEN bulan = '07' THEN jml_debitur ELSE 0 END) AS jd07,
         SUM (CASE WHEN bulan = '08' THEN jml_debitur ELSE 0 END) AS jd08,
         SUM (CASE WHEN bulan = '09' THEN jml_debitur ELSE 0 END) AS jd09,
         SUM (CASE WHEN bulan = '10' THEN jml_debitur ELSE 0 END) AS jd10,
         SUM (CASE WHEN bulan = '11' THEN jml_debitur ELSE 0 END) AS jd11,
         SUM (CASE WHEN bulan = '12' THEN jml_debitur ELSE 0 END) AS jd12,
         SUM (CASE WHEN bulan IN ('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12') THEN jml_debitur ELSE 0 END) AS jdtotal,
         SUM (CASE WHEN bulan = '01' THEN jml_penyaluran ELSE 0 END) AS jp01,
         SUM (CASE WHEN bulan = '02' THEN jml_penyaluran ELSE 0 END) AS jp02,
         SUM (CASE WHEN bulan = '03' THEN jml_penyaluran ELSE 0 END) AS jp03,
         SUM (CASE WHEN bulan = '04' THEN jml_penyaluran ELSE 0 END) AS jp04,
         SUM (CASE WHEN bulan = '05' THEN jml_penyaluran ELSE 0 END) AS jp05,
         SUM (CASE WHEN bulan = '06' THEN jml_penyaluran ELSE 0 END) AS jp06,
         SUM (CASE WHEN bulan = '07' THEN jml_penyaluran ELSE 0 END) AS jp07,
         SUM (CASE WHEN bulan = '08' THEN jml_penyaluran ELSE 0 END) AS jp08,
         SUM (CASE WHEN bulan = '09' THEN jml_penyaluran ELSE 0 END) AS jp09,
         SUM (CASE WHEN bulan = '10' THEN jml_penyaluran ELSE 0 END) AS jp10,
         SUM (CASE WHEN bulan = '11' THEN jml_penyaluran ELSE 0 END) AS jp11,
         SUM (CASE WHEN bulan = '12' THEN jml_penyaluran ELSE 0 END) AS jp12,
         SUM (CASE WHEN bulan IN ('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12') THEN jml_penyaluran ELSE 0 END) AS jptotal
    FROM (  SELECT kode_bank,
                   skema,
                   sektor,
                   tahun,
                   bulan,
                   kode_provinsi,
                   kode_wilayah,
                   kode_pendidikan,
                   kode_pekerjaan,
                   kode_jns_kelamin,
                   kode_marital_sts,
                   SUM (jml_debitur) AS jml_debitur,
                   SUM (jml_penyaluran) AS jml_penyaluran,
                   SUM (jml_outstanding) AS jml_outstanding,
                   SUM (rencana_kredit) AS rencana_kredit
              FROM kur_a_custom_report
             WHERE tahun = :ptahun AND kode_wilayah = :pkabkota AND kode_bank = :pbank
          GROUP BY kode_bank,
                   skema,
                   sektor,
                   tahun,
                   bulan,
                   kode_provinsi,
                   kode_wilayah,
                   kode_pendidikan,
                   kode_pekerjaan,
                   kode_jns_kelamin,
                   kode_marital_sts)
GROUP BY kode_bank,
         skema,
         sektor,
         kode_wilayah
ORDER BY 1, 2;