/* Formatted on 22/09/2025 16:19:39 (QP5 v5.215.12089.38647) */
  SELECT object_name, last_ddl_time, 'SELECT * FROM ' || object_name || '@SIKP_19C ORDER BY 1 DESC;' AS sql_query_cmd
    FROM all_objects@sikp_19c
   WHERE owner = 'USERKUR' AND object_type = 'TABLE' AND object_name LIKE '%ERROR%'
ORDER BY last_ddl_time DESC;

  SELECT *
    FROM BPJS_T_LOG_ERROR@SIKP_19C
ORDER BY 1 DESC;

--  SELECT *
--    FROM TEMP_KUR_BRI_AKAD_KE_ERROR1@SIKP_19C
--ORDER BY 1 DESC;

--  SELECT *
--    FROM TEMP_KUR_BRI_AKAD_KE_ERROR@SIKP_19C
--ORDER BY 1 DESC;

  SELECT *
    FROM TEMP_KUR_LOG_ERROR@SIKP_19C
ORDER BY 7 DESC;

  SELECT *
    FROM ERROR_LOG_REKON_TAGTB_DTL@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_UPLOAD_DIST_TB@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_UPLOAD_DIST@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_UPLOAD_TRAN_UMKM@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_REKON_UMKM_DTL@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_TAGUMKM_DTL@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_TAGTB_DTL@SIKP_19C
ORDER BY 2 DESC;

--  SELECT *
--    FROM KUR_T_DEBITUR_UPDATE_ERROR@SIKP_19C
--ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_UPLOAD_PEMDA@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM LOG_ERROR1@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_UPLOAD_TRANSAKSI@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_UPLOAD_CALON@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_UPLOAD_AKAD@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_REKON_DETIL@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM ERROR_LOG_UPLOAD_KOREKSI@SIKP_19C
ORDER BY 2 DESC;

  SELECT *
    FROM LOG_ERROR@SIKP_19C
ORDER BY 2 DESC;