/* Formatted on 14/02/2025 17:32:26 (QP5 v5.215.12089.38647) */
SELECT * FROM TEMP_INSTALLMENT_TRANSACTION;

SELECT * FROM KUR_T_TRANSAKSI;

  SELECT ID_TRANSAKSI AS TRANSACTION_ID,
         KODE_BANK AS BANK_CODE,
         NOMOR_REKENING AS ACCOUNT_NUMBER,
         LIMIT AS LOAN_AMOUNT,
         TGL_TRANSAKSI AS INSTALLMENT_DATE,
         OUTSTANDING,
         ANGSURAN_POKOK AS PRINCIPAL_INSTALLMENT,
         TGL_PELAPORAN AS LOAN_DUE_DATE
    FROM KUR_T_TRANSAKSI
   WHERE     KODE_BANK = '002'
         AND NOMOR_REKENING IN
                 ('476201002766103', '574601004715105', '310701009993106', '590201007356102', '549901004233106', '098501008420109', '495701006392103', '622501011231107')
ORDER BY BANK_CODE, ACCOUNT_NUMBER, INSTALLMENT_DATE;

  SELECT KODE_BANK || '|' || NOMOR_REKENING, COUNT (TGL_TRANSAKSI) JML_DATA
    FROM KUR_T_TRANSAKSI
   WHERE KODE_BANK <> '990' AND KODE_BANK = '002'
GROUP BY KODE_BANK || '|' || NOMOR_REKENING
  HAVING COUNT (TGL_TRANSAKSI) > 50
ORDER BY JML_DATA DESC;

  SELECT ID_TRANSAKSI AS TRANSACTION_ID,
         KODE_BANK AS BANK_CODE,
         NOMOR_REKENING AS ACCOUNT_NUMBER,
         LIMIT AS LOAN_AMOUNT,
         TGL_TRANSAKSI AS INSTALLMENT_DATE,
         OUTSTANDING,
         ANGSURAN_POKOK AS PRINCIPAL_INSTALLMENT,
         TGL_PELAPORAN AS LOAN_DUE_DATE
    FROM KUR_T_TRANSAKSI
   WHERE NOMOR_REKENING = '310701009993106'
ORDER BY TGL_TRANSAKSI ASC;

SELECT * FROM TEMP_INSTALLMENT_TRANSACTION;

  SELECT A.TRANSACTION_ID,
         A.BANK_CODE,
         A.ACCOUNT_NUMBER,
         A.LOAN_AMOUNT,
         A.INSTALLMENT_DATE,
         A.PRINCIPAL_INSTALLMENT,
         A.OUTSTANDING,
         A.TSEQ,
         NVL (B.NEXT_INSTALLMENT_DATE, A.END_OF_MONTH) AS NEXT_INSTALLMENT_DATE,
         A.END_OF_MONTH,
         A.LOAN_DUE_DATE,
         (NVL (B.NEXT_INSTALLMENT_DATE, A.END_OF_MONTH) - A.INSTALLMENT_DATE) AS NUMBER_OF_INSTEREST_DAYS,
         ROUND ( ( ( (NVL (B.NEXT_INSTALLMENT_DATE, A.END_OF_MONTH) - A.INSTALLMENT_DATE) / 360) * A.OUTSTANDING * 0.0417), 0) AS SUBSIDY_AMOUNT
    FROM     (  SELECT TRANSACTION_ID,
                       BANK_CODE,
                       ACCOUNT_NUMBER,
                       LOAN_AMOUNT,
                       INSTALLMENT_DATE,
                       LAST_DAY (INSTALLMENT_DATE) AS END_OF_MONTH,
                       PRINCIPAL_INSTALLMENT,
                       OUTSTANDING,
                       LOAN_DUE_DATE,
                       ROW_NUMBER () OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY OUTSTANDING DESC) AS TSEQ
                  FROM TEMP_INSTALLMENT_TRANSACTION
                 WHERE ACCOUNT_NUMBER = '310701009993106'
              ORDER BY OUTSTANDING DESC) A
         LEFT JOIN
             (  SELECT TRANSACTION_ID,
                       BANK_CODE,
                       ACCOUNT_NUMBER,
                       LOAN_AMOUNT,
                       INSTALLMENT_DATE AS NEXT_INSTALLMENT_DATE,
                       PRINCIPAL_INSTALLMENT,
                       OUTSTANDING,
                       LOAN_DUE_DATE,
                       ROW_NUMBER () OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY OUTSTANDING DESC) AS TSEQ
                  FROM TEMP_INSTALLMENT_TRANSACTION
                 WHERE ACCOUNT_NUMBER = '310701009993106' AND PRINCIPAL_INSTALLMENT > 0
              ORDER BY OUTSTANDING DESC) B
         ON (A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.TSEQ = B.TSEQ)
ORDER BY A.OUTSTANDING DESC;

  SELECT A.TRANSACTION_ID,
         A.BANK_CODE,
         A.ACCOUNT_NUMBER,
         A.LOAN_AMOUNT,
         A.INSTALLMENT_DATE,
         A.PRINCIPAL_INSTALLMENT,
         A.OUTSTANDING,
         A.TSEQ,
         NVL (B.NEXT_INSTALLMENT_DATE, A.END_OF_MONTH) AS NEXT_INSTALLMENT_DATE,
         A.END_OF_MONTH,
         A.LOAN_DUE_DATE,
         (NVL (B.NEXT_INSTALLMENT_DATE, A.END_OF_MONTH) - A.INSTALLMENT_DATE) AS NUMBER_OF_INSTEREST_DAYS,
         ROUND ( ( ( (NVL (B.NEXT_INSTALLMENT_DATE, A.END_OF_MONTH) - A.INSTALLMENT_DATE) / 360) * A.OUTSTANDING * 0.0417), 0) AS SUBSIDY_AMOUNT
    FROM     (  SELECT TRANSACTION_ID,
                       BANK_CODE,
                       ACCOUNT_NUMBER,
                       LOAN_AMOUNT,
                       INSTALLMENT_DATE,
                       LAST_DAY (INSTALLMENT_DATE) AS END_OF_MONTH,
                       PRINCIPAL_INSTALLMENT,
                       OUTSTANDING,
                       LOAN_DUE_DATE,
                       ROW_NUMBER () OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY OUTSTANDING DESC) AS TSEQ
                  FROM TEMP_INSTALLMENT_TRANSACTION
                 WHERE ACCOUNT_NUMBER = '310701009993106'
              ORDER BY OUTSTANDING DESC) A
         LEFT JOIN
             (  SELECT TRANSACTION_ID,
                       BANK_CODE,
                       ACCOUNT_NUMBER,
                       LOAN_AMOUNT,
                       INSTALLMENT_DATE AS NEXT_INSTALLMENT_DATE,
                       PRINCIPAL_INSTALLMENT,
                       OUTSTANDING,
                       LOAN_DUE_DATE,
                       ROW_NUMBER () OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY OUTSTANDING DESC) AS TSEQ
                  FROM TEMP_INSTALLMENT_TRANSACTION
                 WHERE ACCOUNT_NUMBER = '310701009993106' AND PRINCIPAL_INSTALLMENT > 0
              ORDER BY OUTSTANDING DESC) B
         ON (A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.TSEQ = B.TSEQ)
   WHERE TO_CHAR (A.INSTALLMENT_DATE, 'yyyymm') = '201604'
ORDER BY A.OUTSTANDING DESC;

  SELECT BANK_CODE,
         ACCOUNT_NUMBER,
         LOAN_AMOUNT,
         OUTSTANDING,
         --LOAN_DUE_DATE,
         --INSTALLMENT_DATE,
         --NEXT_INSTALLMENT_DATE,
         PRINCIPAL_INSTALLMENT,
         NUMBER_OF_INSTEREST_DAYS,
         --SUBSIDY_AMOUNT,
         ROW_NUMBER () OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY OUTSTANDING DESC) AS TSEQ
    FROM (  SELECT A.TRANSACTION_ID,
                   A.BANK_CODE,
                   A.ACCOUNT_NUMBER,
                   A.LOAN_AMOUNT,
                   A.INSTALLMENT_DATE,
                   A.PRINCIPAL_INSTALLMENT,
                   A.OUTSTANDING,
                   A.TSEQ,
                   NVL (B.NEXT_INSTALLMENT_DATE, A.END_OF_MONTH) AS NEXT_INSTALLMENT_DATE,
                   A.END_OF_MONTH,
                   A.LOAN_DUE_DATE,
                   (NVL (B.NEXT_INSTALLMENT_DATE, A.END_OF_MONTH) - A.INSTALLMENT_DATE) AS NUMBER_OF_INSTEREST_DAYS,
                   ROUND ( ( ( (NVL (B.NEXT_INSTALLMENT_DATE, A.END_OF_MONTH) - A.INSTALLMENT_DATE) / 360) * A.OUTSTANDING * 0.0417), 0) AS SUBSIDY_AMOUNT
              FROM     (  SELECT TRANSACTION_ID,
                                 BANK_CODE,
                                 ACCOUNT_NUMBER,
                                 LOAN_AMOUNT,
                                 INSTALLMENT_DATE,
                                 LAST_DAY (INSTALLMENT_DATE) AS END_OF_MONTH,
                                 PRINCIPAL_INSTALLMENT,
                                 OUTSTANDING,
                                 LOAN_DUE_DATE,
                                 ROW_NUMBER () OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY OUTSTANDING DESC) AS TSEQ
                            FROM TEMP_INSTALLMENT_TRANSACTION
                           WHERE ACCOUNT_NUMBER = '310701009993106'
                        ORDER BY OUTSTANDING DESC) A
                   LEFT JOIN
                       (  SELECT TRANSACTION_ID,
                                 BANK_CODE,
                                 ACCOUNT_NUMBER,
                                 LOAN_AMOUNT,
                                 INSTALLMENT_DATE AS NEXT_INSTALLMENT_DATE,
                                 PRINCIPAL_INSTALLMENT,
                                 OUTSTANDING,
                                 LOAN_DUE_DATE,
                                 ROW_NUMBER () OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY OUTSTANDING DESC) AS TSEQ
                            FROM TEMP_INSTALLMENT_TRANSACTION
                           WHERE ACCOUNT_NUMBER = '310701009993106' AND PRINCIPAL_INSTALLMENT > 0
                        ORDER BY OUTSTANDING DESC) B
                   ON (A.ACCOUNT_NUMBER = B.ACCOUNT_NUMBER AND A.TSEQ = B.TSEQ)
          ORDER BY A.OUTSTANDING DESC)
ORDER BY OUTSTANDING DESC;