SELECT * FROM TAB WHERE LOWER (TNAME) LIKE '%kur_a%';

SELECT KODE_GRUP_SEKTOR, 
       NAMA_GRUP_SEKTOR,
       SUM (CASE WHEN BULAN = '01' THEN JML_DEBITUR END) AS JD01,
       SUM (CASE WHEN BULAN = '02' THEN JML_DEBITUR END) AS JD02,
       SUM (CASE WHEN BULAN = '03' THEN JML_DEBITUR END) AS JD03,
       SUM (CASE WHEN BULAN = '04' THEN JML_DEBITUR END) AS JD04,
       SUM (CASE WHEN BULAN = '05' THEN JML_DEBITUR END) AS JD05,
       SUM (CASE WHEN BULAN = '06' THEN JML_DEBITUR END) AS JD06,
       SUM (CASE WHEN BULAN = '07' THEN JML_DEBITUR END) AS JD07,
       SUM (CASE WHEN BULAN = '08' THEN JML_DEBITUR END) AS JD08,
       SUM (CASE WHEN BULAN = '09' THEN JML_DEBITUR END) AS JD09,
       SUM (CASE WHEN BULAN = '10' THEN JML_DEBITUR END) AS JD10,
       SUM (CASE WHEN BULAN = '11' THEN JML_DEBITUR END) AS JD11,
       SUM (CASE WHEN BULAN = '12' THEN JML_DEBITUR END) AS JD12,
       SUM (CASE WHEN TAHUN = '2021' THEN JML_DEBITUR END) AS JDTOT,
       SUM (CASE WHEN BULAN = '01' THEN JML_AKAD END) AS JA01,
       SUM (CASE WHEN BULAN = '02' THEN JML_AKAD END) AS JA02,
       SUM (CASE WHEN BULAN = '03' THEN JML_AKAD END) AS JA03,
       SUM (CASE WHEN BULAN = '04' THEN JML_AKAD END) AS JA04,
       SUM (CASE WHEN BULAN = '05' THEN JML_AKAD END) AS JA05,
       SUM (CASE WHEN BULAN = '06' THEN JML_AKAD END) AS JA06,
       SUM (CASE WHEN BULAN = '07' THEN JML_AKAD END) AS JA07,
       SUM (CASE WHEN BULAN = '08' THEN JML_AKAD END) AS JA08,
       SUM (CASE WHEN BULAN = '09' THEN JML_AKAD END) AS JA09,
       SUM (CASE WHEN BULAN = '10' THEN JML_AKAD END) AS JA10,
       SUM (CASE WHEN BULAN = '11' THEN JML_AKAD END) AS JA11,
       SUM (CASE WHEN BULAN = '12' THEN JML_AKAD END) AS JA12,
       SUM (CASE WHEN TAHUN = '2021' THEN JML_AKAD END) AS JATOT,
       SUM (CASE WHEN BULAN = '01' THEN JML_TKI END) AS JT01
FROM KUR_A_REALISASI_PER_SEKTOR
WHERE TAHUN = '2021'
GROUP BY KODE_GRUP_SEKTOR, NAMA_GRUP_SEKTOR
ORDER BY 1;

SELECT SUBSTR(KODE_WILAYAH, 1, 2) AS KODE_PROVINSI, KODE_BANK, 
       SUM (CASE WHEN PERIODE_OUTSTANDING='2015' THEN JML_OUTSTANDING ELSE 0 END) AS JML_AKAD_15, 
       SUM (CASE WHEN PERIODE_OUTSTANDING='2016' THEN JML_OUTSTANDING ELSE 0 END) AS JML_AKAD_16,
       SUM (CASE WHEN PERIODE_OUTSTANDING='2017' THEN JML_OUTSTANDING ELSE 0 END) AS JML_AKAD_17,
       SUM (CASE WHEN PERIODE_OUTSTANDING='2018' THEN JML_OUTSTANDING ELSE 0 END) AS JML_AKAD_18,
       SUM (CASE WHEN PERIODE_OUTSTANDING='2019' THEN JML_OUTSTANDING ELSE 0 END) AS JML_AKAD_19,
       SUM (CASE WHEN PERIODE_OUTSTANDING='2020' THEN JML_OUTSTANDING ELSE 0 END) AS JML_AKAD_20,
       SUM (CASE WHEN PERIODE_OUTSTANDING='2021' THEN JML_OUTSTANDING ELSE 0 END) AS JML_AKAD_21,
       SUM (CASE WHEN PERIODE_OUTSTANDING='2022' THEN JML_OUTSTANDING ELSE 0 END) AS JML_AKAD_22
FROM KUR_A_PENYALURAN_PEMDA_KANWIL
WHERE SUBSTR(KODE_WILAYAH, 1, 1) = '3'
GROUP BY SUBSTR(KODE_WILAYAH, 1, 2), KODE_BANK
ORDER BY KODE_PROVINSI, KODE_BANK
