/* Formatted on 06/03/2024 14:02:30 (QP5 v5.215.12089.38647) */
SELECT * FROM SSRG_T_AKAD;


SELECT A.ID,
       A.NIK,
       A.NPWP,
       A.NAMA,
       TO_CHAR (A.TGL_LAHIR, 'yyyy-mm-dd') AS TGL_LAHIR,
       (A.JNS_KELAMIN || ' -- ' || B.NAMA) AS JNS_KELAMIN,
       (A.MARITAS_STS || ' -- ' || C.DESKRIPSI) AS MARITAL_STS,
       (A.PENDIDIKAN || ' -- ' || D.DESKRIPSI) AS PENDIDIKAN,
       (A.PEKERJAAN || ' -- ' || E.DESKRIPSI) AS PEKERJAAN,
       UPPER (TRIM (A.ALAMAT)) AS ALAMAT_DOMISILI,
       (A.KODE_KABKOTA || ' -- ' || UPPER (F.NAMA_WILAYAH)) AS KABKOTA,
       (SUBSTR (A.KODE_KABKOTA, 1, 2) || ' -- ' || UPPER (G.NAMA_WILAYAH)) AS PROVINSI,
       A.KODE_POS,
       A.NO_HP
  FROM SSRG_T_DEBITUR A
       LEFT JOIN KUR_R_JENIS_KELAMIN B
          ON (A.JNS_KELAMIN = B.KODE)
       LEFT JOIN KUR_R_MARITAL_STS C
          ON (A.MARITAS_STS = C.MARITAL_STS)
       LEFT JOIN KUR_R_PENDIDIKAN D
          ON (A.PENDIDIKAN = D.PENDIDIKAN)
       LEFT JOIN KUR_R_PEKERJAAN E
          ON (A.PEKERJAAN = E.PEKERJAAN)
       LEFT JOIN KUR_R_WILAYAH F
          ON (A.KODE_KABKOTA = F.KODE_WILAYAH)
       LEFT JOIN KUR_R_WILAYAH_PROPINSI G
          ON (SUBSTR (A.KODE_KABKOTA, 1, 2) = G.KODE_WILAYAH);


SELECT A.NIK,
       A.NAMA,
       A.IJIN_USAHA,
       TO_CHAR (A.MULAI_USAHA, 'yyyy-mm-dd') AS MULAI_USAHA,
       A.MODAL_USAHA,
       A.ALAMAT_USAHA,
       A.JUMLAH_PEKERJA,
       A.JUMLAH_KREDIT,
       NVL (A.SUBSIDI_SBLM, 'X') AS SUBSIDI_SBLM,
       NVL (A.LINKAGE, 'N/A') AS LINKAGE
  FROM SSRG_T_DEBITUR A;

SELECT A.NIK,
       (A.KODE_BANK || ' -- ' || UPPER (B.NAMA_BANK)) AS BANK,
       A.REKENING_BARU AS NOMOR_REKENING,
       A.NOMOR_AKAD,
       TO_CHAR (A.TGL_AKAD, 'YYYY-MM-DD') AS TGL_AKAD,
       TO_CHAR (A.TGL_JATUH_TEMPO, 'YYYY-MM-DD') AS TGL_JATUH_TEMPO,
       A.NILAI_AKAD,
       C.NOMOR_RESI,
       NVL (A.NM_KEL, 'N/A') AS NAMA_KELOMPOK,
       TO_CHAR (A.TGL_UPDATE, 'YYYY-MM-DD') AS TGL_UPDATE
  FROM SSRG_T_AKAD A
       LEFT JOIN KUR_R_BANK B
          ON (A.KODE_BANK = B.KODE_BANK)
       LEFT JOIN SSRG_T_RESIGUDANG C
          ON (A.NIK = C.NIK);


SELECT A.NIK,
       NVL (B.NAMA, 'Nama tidak ditemukan di data debitur') AS NAMA,
       A.NOMOR_RESI,
       (A.REG_GUDANG || C.NAMA_GUDANG) AS NAMA_GUDANG,
       (A.KOMODITAS || ' -- ' || UPPER (D.DESKRIPSI)) AS KOMODITAS,
       A.NILAI_KOMODITAS,
       TO_CHAR (A.TGL_PENJAMINAN, 'YYYY-MM-DD') AS TGL_TERBIT,
       TO_CHAR (A.TGL_JATUH_TEMPO, 'YYYY-MM-DD') AS TGL_JATUH_TEMPO,
       TO_CHAR (A.TGL_UPDATE, 'YYYY-MM-DD') AS TGL_UPDATE
  FROM SSRG_T_RESIGUDANG A
       LEFT JOIN SSRG_T_DEBITUR B
          ON (A.NIK = B.NIK)
       LEFT JOIN SSRG_T_GUDANG C
          ON (A.REG_GUDANG = C.KODE_REGISTRASI)
       LEFT JOIN SSRG_R_KOMODITAS D
          ON (A.KOMODITAS = D.KODE_KOMODITAS);

  SELECT *
    FROM KUR_R_WILAYAH
   WHERE SUBSTR (KODE_WILAYAH, 1, 2) = '35'
ORDER BY 1 ASC;