CREATE TABLE SSRG_A_CUSTOM_REPORT_ALT AS
	SELECT A.KODE_BANK,
		   A.NAMA_BANK,
		   A.TAHUN,
		   A.BULAN,
		   A.NAMA_BULAN,
		   TO_CHAR (A.KODE_JNS_KELAMIN) KODE_JNS_KELAMIN,
		   A.NAMA_JNS_KELAMIN,
		   TO_CHAR (KODE_MARITAL_STS) KODE_MARITAL_STS,
		   A.NAMA_MARITAL_STS,
		   TO_CHAR (A.KODE_PENDIDIKAN) KODE_PENDIDIKAN,
		   A.NAMA_PENDIDIKAN,
		   TO_CHAR (A.KODE_PEKERJAAN) KODE_PEKERJAAN,
		   A.NAMA_PEKERJAAN,
		   A.KODE_PROVINSI,
		   A.NAMA_PROVINSI,
		   A.KODE_KABKOTA,
		   A.NAMA_KABKOTA,
		   A.KODE_POS,
		   A.KODE_SKEMA,
		   A.KODE_SEKTOR_GROUP,
		   A.NAMA_SEKTOR_GROUP,
		   A.KODE_SEKTOR,
		   A.NAMA_SEKTOR,
		   A.KODE_GUDANG,
		   A.NAMA_GUDANG,
		   A.KODE_KOMODITAS,
		   A.NAMA_KOMODITAS,
		   A.RENCANA_KREDIT,
		   A.JML_PEKERJA,
		   A.JML_DEBITUR,
		   A.JML_PENYALURAN,
		   A.JML_OUTSTANDING,
		   TO_CHAR (CURRENT_TIMESTAMP, 'yyyy/mm/dd hh24:mi:ss') LAST_UPDATED
	  FROM SSRG_A_CUSTOM_REPORT A;
	  
	  
	  
CREATE OR REPLACE PROCEDURE PROC_SSRG_A_CUSTOM_REPORT_NEW
IS
  v_table_exists NUMBER := 0;
BEGIN
  /* 1. Cek apakah tabel sudah ada */
  EXECUTE IMMEDIATE
    'SELECT COUNT(*)
     FROM   USER_TABLES
     WHERE  table_name = ''SSRG_A_CUSTOM_REPORT_NEW'''
    INTO v_table_exists;

  /* 2. Jika ada, drop dulu */
  IF v_table_exists = 1 THEN
    EXECUTE IMMEDIATE 'DROP TABLE SSRG_A_CUSTOM_REPORT_NEW';
    DBMS_OUTPUT.PUT_LINE('Tabel SSRG_A_CUSTOM_REPORT_NEW di-drop.');
  END IF;

  /* 3. Create tabel baru via CTAS */
  EXECUTE IMMEDIATE '
	CREATE TABLE SSRG_A_CUSTOM_REPORT_ALT AS
		SELECT A.KODE_BANK,
			   A.NAMA_BANK,
			   A.TAHUN,
			   A.BULAN,
			   A.NAMA_BULAN,
			   TO_CHAR (A.KODE_JNS_KELAMIN) KODE_JNS_KELAMIN,
			   A.NAMA_JNS_KELAMIN,
			   TO_CHAR (KODE_MARITAL_STS) KODE_MARITAL_STS,
			   A.NAMA_MARITAL_STS,
			   TO_CHAR (A.KODE_PENDIDIKAN) KODE_PENDIDIKAN,
			   A.NAMA_PENDIDIKAN,
			   TO_CHAR (A.KODE_PEKERJAAN) KODE_PEKERJAAN,
			   A.NAMA_PEKERJAAN,
			   A.KODE_PROVINSI,
			   A.NAMA_PROVINSI,
			   A.KODE_KABKOTA,
			   A.NAMA_KABKOTA,
			   A.KODE_POS,
			   A.KODE_SKEMA,
			   A.KODE_SEKTOR_GROUP,
			   A.NAMA_SEKTOR_GROUP,
			   A.KODE_SEKTOR,
			   A.NAMA_SEKTOR,
			   A.KODE_GUDANG,
			   A.NAMA_GUDANG,
			   A.KODE_KOMODITAS,
			   A.NAMA_KOMODITAS,
			   A.RENCANA_KREDIT,
			   A.JML_PEKERJA,
			   A.JML_DEBITUR,
			   A.JML_PENYALURAN,
			   A.JML_OUTSTANDING,
			   TO_CHAR (CURRENT_TIMESTAMP, ''yyyy/mm/dd hh24:mi:ss'') LAST_UPDATED
		  FROM SSRG_A_CUSTOM_REPORT A
	';  -- CTAS tanpa data (hanya struktur)

  DBMS_OUTPUT.PUT_LINE('Tabel SSRG_A_CUSTOM_REPORT_NEW berhasil dibuat.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
    RAISE;  -- opsional: biarkan exception naik ke caller
END PROC_SSRG_A_CUSTOM_REPORT_NEW;
/