/* Formatted on 25/06/2024 14:03:09 (QP5 v5.215.12089.38647) */
SELECT '0170B131220427000556' AS NOMOR_REKENING,
       '2024-05-19' AS TGL_TRANSAKSI,
       '2024-05-20' AS TGL_PELAPORAN,
       '55000000' AS LIMIT,
       '52708333' AS OUTSTANDING,
       '2291667' AS ANGSURAN_POKOK,
       '1' AS KOLEKTIBILITAS,
       '1' AS KODE_TRANSAKSI,
       '002' AS KODE_BANK
  FROM DUAL;

SELECT :VNOMOR_REKENING AS NOMOR_REKENING,
       TO_DATE (:VTGL_TRANSAKSI, 'YYYY-MM-DD') AS TGL_TRANSAKSI,
       TO_DATE (:VTGL_PELAPORAN, 'YYYY-MM-DD') AS TGL_PELAPORAN,
       TO_NUMBER (:VLIMIT) AS LIMIT,
       TO_NUMBER (:VOUTSTANDING) AS OUTSTANDING,
       TO_NUMBER (:VANGSURAN_POKOK) AS ANGSURAN_POKOK,
       TO_NUMBER (:VKOLEKTIBILITAS) AS KOLEKTIBILITAS,
       :VKODE_BANK AS KODE_BANK
  FROM DUAL;

SELECT A.*,
       (A.ANGSURAN_POKOK + A.OUTSTANDING) KUMULATIF,
       B.TGL_AKAD,
       B.TGL_JATUH_TEMPO,
       B.NILAI_AKAD,
       CASE WHEN TRUNC (A.TGL_TRANSAKSI) <= TRUNC (A.TGL_PELAPORAN) THEN 'OK' WHEN TRUNC (A.TGL_TRANSAKSI) > TRUNC (A.TGL_PELAPORAN) THEN 'FAILED' END AS RULE_02,
       CASE WHEN A.OUTSTANDING <= A.LIMIT THEN 'OK' WHEN A.OUTSTANDING > A.LIMIT THEN 'FAILED' WHEN (A.OUTSTANDING IS NULL OR A.LIMIT IS NULL) THEN 'FAILED' END AS RULE_03,
       CASE WHEN A.ANGSURAN_POKOK <= A.OUTSTANDING THEN 'OK' WHEN A.ANGSURAN_POKOK > A.OUTSTANDING THEN 'FAILED' END AS RULE_04,
       CASE WHEN A.ANGSURAN_POKOK <= A.LIMIT THEN 'OK' WHEN A.ANGSURAN_POKOK > A.LIMIT THEN 'FAILED' END AS RULE_05,
       CASE WHEN TRUNC (A.TGL_TRANSAKSI) >= TRUNC (B.TGL_AKAD) THEN 'OK' WHEN TRUNC (A.TGL_TRANSAKSI) < TRUNC (B.TGL_AKAD) THEN 'FAILED' END AS RULE_06,
       CASE WHEN TRUNC (A.TGL_TRANSAKSI) <= TRUNC (B.TGL_JATUH_TEMPO) THEN 'OK' WHEN TRUNC (A.TGL_TRANSAKSI) > TRUNC (B.TGL_JATUH_TEMPO) THEN 'FAILED' END AS RULE_07,
       CASE WHEN A.LIMIT = B.NILAI_AKAD THEN 'OK' ELSE 'FAILED' END AS RULE_08,
       CASE WHEN (A.ANGSURAN_POKOK + A.OUTSTANDING) = OUTSBEFORE THEN 'OK' ELSE 'FAILED' END AS RULE_09,
       CASE
           WHEN ANGSURAN_POKOK = 0 THEN (CASE WHEN A.OUTSTANDING = A.LIMIT THEN 'OK' ELSE 'FAILED' END)
           WHEN ANGSURAN_POKOK > 0 THEN (CASE WHEN A.OUTSTANDING < A.LIMIT THEN 'OK' ELSE 'FAILED' END)
           ELSE 'FAILED'
       END
           AS RULE_10
  FROM (SELECT :VNOMOR_REKENING AS NOMOR_REKENING,
               TO_DATE (:VTGL_TRANSAKSI, 'YYYY-MM-DD') AS TGL_TRANSAKSI,
               TO_DATE (:VTGL_PELAPORAN, 'YYYY-MM-DD') AS TGL_PELAPORAN,
               TO_NUMBER (:VLIMIT) AS LIMIT,
               TO_NUMBER (:VOUTSTANDING) AS OUTSTANDING,
               TO_NUMBER (:VANGSURAN_POKOK) AS ANGSURAN_POKOK,
               TO_NUMBER (:VKOLEKTIBILITAS) AS KOLEKTIBILITAS,
               :VKODE_BANK AS KODE_BANK
          FROM DUAL) A
       LEFT JOIN SSRG_T_AKAD B
           ON (:VKODE_BANK = B.KODE_BANK AND :VNOMOR_REKENING = B.REKENING_BARU)
       LEFT JOIN (SELECT KODE_BANK, NO_REK, OUTSTANDING AS OUTSBEFORE
                    FROM SSRG_T_TRANSAKSI
                   WHERE     KODE_BANK = :VKODE_BANK
                         AND NO_REK = :VNOMOR_REKENING
                         AND TO_CHAR (TGL_TRANSAKSI, 'YYYY-MM-DD') = (SELECT TO_CHAR (MAX (TGL_TRANSAKSI), 'YYYY-MM-DD')
                                                                        FROM SSRG_T_TRANSAKSI
                                                                       WHERE KODE_BANK = :VKODE_BANK AND NO_REK = :VNOMOR_REKENING)) C
           ON (A.NOMOR_REKENING = C.NO_REK);

SELECT *
  FROM SSRG_T_TRANSAKSI@SIKP_19c
 WHERE NO_REK = '7301033906101';

SELECT *
  FROM SSRG_T_TRANSAKSI
 WHERE     KODE_BANK = :VKODE_BANK
       AND NO_REK = :VNOMOR_REKENING
       AND TO_CHAR (TGL_TRANSAKSI, 'YYYY-MM-DD') = (SELECT TO_CHAR (MAX (TGL_TRANSAKSI), 'YYYY-MM-DD')
                                                      FROM SSRG_T_TRANSAKSI
                                                     WHERE KODE_BANK = :VKODE_BANK AND NO_REK = :VNOMOR_REKENING);

SELECT *
  FROM SSRG_T_AKAD
 WHERE KODE_BANK = :VKODE_BANK AND REKENING_BARU = :VNOMOR_REKENING;

SELECT *
  FROM SSRG_T_TRANSAKSI A, SSRG_T_AKAD B
 WHERE A.NO_REK = B.REKENING_BARU AND A.KODE_BANK = '451';

  SELECT OUTSTANDING
    FROM SSRG_T_TRANSAKSI
   WHERE NO_REK = :VNOMOR_REKENING
ORDER BY TGL_TRANSAKSI DESC