/*
  :new.CREATED_AT := SYSDATE;
  :new.UPDATED_AT := SYSDATE;
*/

CREATE TRIGGER IC_H_LAT_TRG1
   BEFORE UPDATE
   ON USRINCRIMA.IC_H_LAT
   FOR EACH ROW
BEGIN
   :new.UPDATED_AT := CURRENT_TIMESTAMP ();
END;


/* Formatted on 04/12/2023 14:27:16 (QP5 v5.215.12089.38647) */
CREATE OR REPLACE TRIGGER T_LED_TRG_KIRIM
   BEFORE UPDATE OF STATUS
   ON T_LED
   FOR EACH ROW
BEGIN
   -- Cek apakah nilai kolom_pemicu berubah
   IF :old.STATUS != :new.STATUS
   THEN
      :new.TGL_KIRIM := SYSDATE;
   END IF;
EXCEPTION
   WHEN OTHERS
   THEN
      DBMS_OUTPUT.put_line (SQLCODE);
END T_LED_TRG_KIRIM;
/